name: gatsby build & deploy

on:
  push:
    branches:
      - dev
jobs:
  deploy:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: gatsby build
        env:
          GH_API_KEY: ${{ secrets.API_KEY }}
        run: npm run build

      - name: deploy
        uses: maxheld83/ghpages@v0.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.API_KEY }}
          GH_PAT: ${{ secrets.API_KEY }}
          BUILD_DIR: 'public/'
